steps:
  # Build the Docker image for app1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-repo/quickstart-image', './app1']
    id: 'Build Docker Image'

  # Push the Docker image for app1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-repo/quickstart-image']
    id: 'Push Docker Image'

  # Build the Docker image for app2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-repo/flask-image', './app2']
    id: 'Build Docker Image2'

  # Push the Docker image for app2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-repo/flask-image']
    id: 'Push Docker Image2'

  # Apply deployment configurations and create a release using Google Cloud Deploy
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file deploy/dev.yaml --region=us-central1
      gcloud deploy apply --file deploy/prod.yaml --region=us-central1


      # Create releases for app1 and app2
      gcloud deploy releases create 'app1-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline1 --region=us-central1 --from-k8s-manifest=./kubernetes/app1.yaml
      gcloud deploy releases create 'app2-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline1 --region=us-central1 --from-k8s-manifest=./kubernetes/app2.yaml


options:
  logging: CLOUD_LOGGING_ONLY


